# Generated by Django 3.1.7 on 2021-03-08 12:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture_link', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('date_joined', models.DateField(default=datetime.date(2021, 3, 8), editable=False)),
                ('phone_number', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('PAN_number', models.CharField(editable=False, max_length=10)),
                ('Account_number', models.CharField(editable=False, max_length=18)),
                ('IFSC_number', models.CharField(editable=False, max_length=11)),
            ],
        ),
    ]
