# Generated by Django 3.1.7 on 2021-03-08 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0002_auto_20210308_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
