# Generated by Django 3.1.7 on 2021-03-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0003_auto_20210308_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='Account_number',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='createpractioner',
            name='IFSC_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='createpractioner',
            name='PAN_number',
            field=models.CharField(max_length=10),
        ),
    ]
