# Generated by Django 3.1.7 on 2021-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0006_auto_20210308_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.CharField(default='P92661', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
