# Generated by Django 3.1.7 on 2021-03-09 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0020_auto_20210309_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.CharField(default='Pc2f84', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
