# Generated by Django 3.1.7 on 2021-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0021_auto_20210309_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.CharField(default='P0bc1a', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
