# Generated by Django 3.1.7 on 2021-03-09 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0025_auto_20210309_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='date_joined',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
