# Generated by Django 3.1.7 on 2021-03-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0031_auto_20210309_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.CharField(default='Pdccd6', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
