# Generated by Django 3.1.7 on 2021-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0033_auto_20210310_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.CharField(default='P62864', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
