# Generated by Django 3.1.7 on 2021-03-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0040_auto_20210310_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.AutoField(default='P7560e', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
