# Generated by Django 3.1.7 on 2021-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0042_auto_20210310_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpractioner',
            name='dr_id',
            field=models.CharField(default='Pce7a5', editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='createpractioner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
