# Generated by Django 3.1.7 on 2021-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0043_auto_20210310_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpractioner',
            name='id',
        ),
        migrations.AlterField(
            model_name='createpractioner',
            name='dr_id',
            field=models.CharField(default='Pdaa8e', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='createpractioner',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
