# Generated by Django 3.1.7 on 2021-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0044_auto_20210310_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpractioner',
            name='dr_id',
        ),
        migrations.AddField(
            model_name='createpractioner',
            name='id',
            field=models.CharField(default='P17f73', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
