# Generated by Django 3.1.7 on 2021-03-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0004_auto_20210309_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='end2',
            field=models.TimeField(auto_now=True, verbose_name='End-2(hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='available',
            name='start2',
            field=models.TimeField(auto_now=True, verbose_name='Start-2(hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='available',
            name='end1',
            field=models.TimeField(verbose_name='End(hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='available',
            name='start1',
            field=models.TimeField(verbose_name='Start(hh:mm:ss)'),
        ),
    ]
