# Generated by Django 3.1.7 on 2021-03-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0005_auto_20210309_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='end2',
        ),
        migrations.RemoveField(
            model_name='available',
            name='start2',
        ),
    ]
