# Generated by Django 3.1.7 on 2021-03-09 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0006_auto_20210309_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('slots', models.JSONField()),
            ],
        ),
    ]
