# Generated by Django 3.1.7 on 2021-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0008_auto_20210309_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='id',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
