# Generated by Django 3.1.7 on 2021-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0009_auto_20210309_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='available',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slots',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
