# Generated by Django 3.1.7 on 2021-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0013_auto_20210310_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='available',
        ),
        migrations.AlterField(
            model_name='available',
            name='id',
            field=models.CharField(default='xyz', max_length=6, primary_key=True, serialize=False),
        ),
    ]
