# Generated by Django 3.1.7 on 2021-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practioners', '0014_auto_20210310_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='id',
            field=models.UUIDField(default='YourID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slots',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
