# Generated by Django 3.1.7 on 2021-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSlots',
            fields=[
                ('doctor_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
