# Generated by Django 3.1.7 on 2021-03-11 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0002_auto_20210310_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0890ab5-9e6b-45f8-8f92-7dbb31c15ed9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
