# Generated by Django 3.1.7 on 2021-03-12 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0004_auto_20210312_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f93ce0a-954d-43d9-9bc1-90b761e32291'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.UUIDField(default=uuid.UUID('034f8759-02f2-496c-8dc2-bd2d44229709'), editable=False, primary_key=True, serialize=False),
        ),
    ]
