# Generated by Django 3.1.7 on 2021-03-12 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Visitors', '0005_auto_20210312_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentverify',
            old_name='app_id',
            new_name='dr_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.UUID('739e05ad-dcd2-400c-93e9-55416a971601'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d2a9ec85-d426-4856-be19-89b489c9f1eb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
